FROM ubuntu:18.04
RUN apt-get update && apt-get install -y net-tools &&  apt-get install -y wpan-tools && apt-get install -y iputils-ping && apt install -y iproute2 && apt install -y netcat && apt-get install -y tcpdump
CMD bash
